libname fit 'P:\FIT';
*;
%macro onesided(outdat, fitstat);
	ods exclude all;
	proc means data=&outdat.;
		class N sim;
		var &fitstat.;
		output out=max_&fitstat. max(&fitstat.)=max_&fitstat.;
	run;
	proc sort data=max_&fitstat.;
		by N;
	run;
	proc summary data=max_&fitstat.;
		where N ne .;
		by N;
		var max_&fitstat.;
		output out=CV_&fitstat._percentiles(drop=_TYPE_ _FREQ_) p95=p95 p99=p99;
	run;
	data CV_&fitstat._percentiles;
		set CV_&fitstat._percentiles;
		P0=0;
	run;
	ods exclude none;
	proc sgplot data=cv_&fitstat._percentiles;
		band x=N lower=P0 upper=P99 / fillattrs=(color=blue transparency=0.6) legendlabel='99%';
		series x=N y=P99 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		band x=N lower=P0 upper=P95 / fillattrs=(color=green transparency=0.6) legendlabel='95%';
		series x=N y=P95 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		keylegend / valueattrs=(size=13);
		yaxis label="&fitstat." labelattrs=(size=13) valueattrs=(size=13);
		xaxis labelattrs=(size=13) valueattrs=(size=13);
	run;
%mend onesided;
%macro twosided(outdat, fitstat);
	ods exclude all;
	proc means data=&outdat.;
		class N sim;
		var &fitstat.;
		output out=minmax_&fitstat. min(&fitstat.)=min_&fitstat. max(&fitstat.)=max_&fitstat.;
	run;
	proc sort data=minmax_&fitstat.;
		by N;
	run;
	proc univariate data=minmax_&fitstat.;
		where N ne .;
		by N;
		var min_&fitstat.;
		output out=min_&fitstat._percentiles pctlpts=0.5 2.5 pctlpre=P;
	run;
	proc univariate data=minmax_&fitstat.;
		where N ne .;
		by N;
		var max_&fitstat.;
		output out=max_&fitstat._percentiles pctlpts=97.5 99.5 pctlpre=P;
	run;
	data CV_&fitstat._percentiles;
		merge min_&fitstat._percentiles max_&fitstat._percentiles;
	run;
	ods exclude none;
	proc sgplot data=cv_&fitstat._percentiles;
		band x=N lower=P0_5 upper=P99_5 / fillattrs=(color=blue transparency=0.6) legendlabel='99%';
		series x=N y=P0_5 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		series x=N y=P2_5 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		band x=N lower=P2_5 upper=P97_5 / fillattrs=(color=green transparency=0.6) legendlabel='95%';
		keylegend / valueattrs=(size=13);
		series x=N y=P97_5 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		series x=N y=P99_5 / lineattrs=(color=black thickness=2 pattern=20) curvelabel='';
		yaxis label="&fitstat." labelattrs=(size=13) valueattrs=(size=13);
		xaxis labelattrs=(size=13) valueattrs=(size=13);
	run;
%mend twosided;
*;
title '10 items';
%onesided(fit.out_pw_i10, chisq);
%twosided(fit.out_pw_i10, FitResid);
%onesided(fit.out_pw_i10, FValue); 
%twosided(fit.out_pw_i10, infit);
%twosided(fit.out_pw_i10, infit_t);
%twosided(fit.out_pw_i10, outfit);
%twosided(fit.out_pw_i10, outfit_t);
*;
title '12 items';
%onesided(fit.out_pw_i12, chisq);
%twosided(fit.out_pw_i12, FitResid);
%onesided(fit.out_pw_i12, FValue); 
%twosided(fit.out_pw_i12, infit);
%twosided(fit.out_pw_i12, infit_t);
%twosided(fit.out_pw_i12, outfit);
%twosided(fit.out_pw_i12, outfit_t);
*;
title 'AMTS';
%onesided(fit.out_AMTS, chisq);
%twosided(fit.out_AMTS, FitResid);
%onesided(fit.out_AMTS, FValue); 
%twosided(fit.out_AMTS, infit);
%twosided(fit.out_AMTS, infit_t);
%twosided(fit.out_AMTS, outfit);
%twosided(fit.out_AMTS, outfit_t);
title ' ';

